

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["TestService/TestService.csproj", "TestService/"]
RUN dotnet restore "TestService/TestService.csproj"
COPY . .
WORKDIR "/src/TestService"
RUN dotnet build "TestService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TestService.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "test", "TestService.dll"]